### ISSUE TITLE
Feedback sessie vrijdag 07-02-'20

### ISSUE THREAD

**Issue by thijsbordewijk** [charder001/web-app-from-scratch-1920#1]
- Update readme.md file with concept etc.

https://github.com/charder001/web-app-from-scratch-1920/blob/36779605edbade5ad27a0988df118243831662fd/docs/js/app.js#L12-L16

 - Useful information for me, didn't know i could put multiple datapoints in 1 variable.

https://github.com/charder001/web-app-from-scratch-1920/blob/36779605edbade5ad27a0988df118243831662fd/docs/js/app.js#L29-L31

- Also useful for me. had not yet thought of the error message if the fetch did not work.

**Comment by charder001** [comment]
Glad my code was of help 👍
