### ISSUE TITLE
Var, const and let

### ISSUE THREAD

**Issue by thijsbordewijk** [charder001/web-app-from-scratch-1920#10]
You used var, let and const in your js. choose one.

https://github.com/charder001/web-app-from-scratch-1920/blob/a5c5f40f96aa3ce2c096539646b1fe247406e28c/docs/js/app.js#L24

**Comment by Mennauu** [comment]
It's not about choosing one, it's about choosing the right one per specific case. 

FYI: https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75

**Comment by charder001** [comment]
Read the medium article and adjusted my code accordingly!
